### ISSUE TITLE
Pyramid 1.10 support

### ISSUE THREAD

**Issue by Epithumia** [Cito/pyramid_ldap3#11]
Pyramid 1.10 was released not too long ago, and one of the deprecations (`pyramid.config.Configurator.set_request_property`, cf. https://github.com/Pylons/pyramid/pull/3368) breaks pyramid_ldap3.

Fortunately, the fix seems to be a simple case of using the non-deprecated method. So, in https://github.com/Cito/pyramid_ldap3/blob/37b3337cea3e26ede8ce2f5bbb6602f08535b305/pyramid_ldap3/__init__.py#L368 replace it with `add_request_method`.

I suppose something might have to be done with https://github.com/Cito/pyramid_ldap3/blob/37b3337cea3e26ede8ce2f5bbb6602f08535b305/tests/__init__.py#L36 too, not sure.

**Comment by Cito** [comment]
Thanks for the heads-up, I'll care about that.

**Comment by Cito** [comment]
This has been fixed in version 0.4 now.

**Comment by Epithumia** [comment]
Awesome. Thanks for the fast update.
