### ISSUE TITLE
ldap3 REUSABLE does not appear to support thread safety.

### ISSUE THREAD

**Issue by hoopdoopdoop** [Cito/pyramid_ldap3#16]
I am experiencing frequent segmentation faults when using LDAP authentication, especially with no caching and a high volume of requests being authenticated.  Upon digging in, I found the following, which I believe may be the problem:

From the ldap3 documentation: 

Thread safe strategies
In multithreaded programs you must use on of SAFE_SYNC (synchronous connection strategy), SAFE_RESTARTABLE (restartable syncronous connection strategy) or ASYNC (asynchronous connection strategy).  pyramid_ldap3 uses REUSABLE, which does not appear to explicitly support thread safety.

**Comment by Cito** [comment]
I'm very sorry, but I can no longer maintain this project. I have added a note about this to the README now.
