### ISSUE TITLE
Client is rejected by the server

### ISSUE THREAD

**Issue by indecenti** [Cito/pyramid_ldap3#5]
I attempt access to a ldap server having timeout (InitRecvTimeout) to 120 seconds. sometimes the client is rejected by the server with the following error:

```
20160309-100235 - SIGPIPE: writing to a closed pipe/socket/fd (probably the client disconnected) !!!
LDAPMaximumRetriesError: restartable connection failed to send
Exception history:
    0 2016-03-09 10:01:35.222385 : <class 'ldap3.core.exceptions.LDAPSocketSendError'> - socket sending error[Errno 104] Connection reset by peer
    1 2016-03-09 10:01:37.224810 : <class 'AttributeError'> - 'Connection' object has no attribute 'close'
```

how can I solve the problem without having to increase the timeout on the server?

thank you so much!

Nicola

**Comment by Cito** [comment]
Maybe you can experiment with using a lower pool_lifetime. The default is 3600 seconds. I just made it configurable in the master branch.

**Comment by delijati** [comment]
I had to set `use_pool=False` to get my ldap connection working, even setting `pool_lifetime=10` had no effect.

**Comment by Cito** [comment]
You can try upgrading the underlying ldap3 module. A new version has just been released.

**Comment by delijati** [comment]
Even with upgrading it didn't changed. So i had to set `use_pool=False`, this works. Could you make a new release of `pyramid_ldap3`.

**Comment by Cito** [comment]
A new release with the `pool_lifetime` parameter has been published now.

**Comment by link89** [comment]
I experience same error with following code
`ad_cli = Connection(server, user=CONFIG['ad']['user'], password=CONFIG['ad']['password'],
                    auto_bind=True, pool_size=2, pool_lifetime=300)
`
It seems pool_lifttime is not work as expect.
