### ISSUE TITLE
ldap3 constants not valid

### ISSUE THREAD

**Issue by pplettner** [Cito/pyramid_ldap3#6]
Hi,

when pip installing the latest version of pyramid_ldap3 (currently 0.2.4), it retrieves v2 of ldap3 automatically as a dependency (currently 2.0.9). However, using them in my Pyramid setup yields this error:

`File "~/venv/lib/python3.5/site-packages/pyramid_ldap3/__init__.py", line 252, in <module>`
    `scope=ldap3.SEARCH_SCOPE_SINGLE_LEVEL, attributes=None,`
`AttributeError: module 'ldap3' has no attribute 'SEARCH_SCOPE_SINGLE_LEVEL'`

and the module doesn't load at all. Downgrading to ldap3 v1.4.0 solves this. Could you take a look, or maybe force a ldap3 downgrade for current version in the meantime?

Thanks a lot,
Patrick

**Comment by Cito** [comment]
Thanks for the notification. I will try to make it compatible with v2 this week.

**Comment by Cito** [comment]
I have pushed a 0.3 release of pyramid_ldap that is compatible with ldap3 version 2 now. If you want to use older ldap3 versions, you can use pyramid_ldap 0.2.5 which restricts the ldap3 version. Let me know if there are still any problems.
