### ISSUE TITLE
Updates for links and theme

### ISSUE THREAD

**Issue by stevepiercy** [Cito/pyramid_ldap3#8]
A little bird in IRC mentioned this package. I've added it to:
https://trypyramid.com/resources-extending-pyramid.html

However, I noticed a few things I would like to run by you before submitting a PR.

* Docs do not use HTTPS. If you use the theme package https://github.com/pylons/pylons-sphinx-themes then you can use HTTPS for docs URLs.
* Some links are out of date, including http://pylonsproject.org/ -> https://pylonsproject.org/
* Use HTTPS for docs.

If you like, I'd be happy to submit a PR with these and whatever other housecleaning chores for docs would be necessary.

**Comment by Cito** [comment]
Thank you, Steve. I made some updates - if anything is still missing, let me know or send a PR.

**Comment by stevepiercy** [comment]
Hey @Cito I found a couple more after running `make linkcheck`, and submitted a PR #9. That should wrap up this issue, too.
